export declare const privType = "OpenSCD-SLD-Layout";
export declare const sldNs = "https://openscd.org/SCL/SSD/SLD/v0";
export declare const xmlnsNs = "http://www.w3.org/2000/xmlns/";
export declare const svgNs = "http://www.w3.org/2000/svg";
export declare const xlinkNs = "http://www.w3.org/1999/xlink";
export declare const eqTypes: readonly ["CAB", "CAP", "CBR", "CTR", "DIS", "GEN", "IFL", "LIN", "MOT", "REA", "RES", "SAR", "SMC", "VTR"];
export type EqType = (typeof eqTypes)[number];
export declare function isEqType(str: string): str is EqType;
export declare const ringedEqTypes: Set<string>;
export declare const singleTerminal: Set<string>;
export declare function setSLDAttributes(element: Element, nsPrefix: string, values: Record<string, string>): void;
export declare function getSLDAttributes(element: Element, key: string): string | null;
export declare function busSections(element: Element): Element[];
export declare function isBusBar(element: Element): boolean;
export declare function makeBusBar(doc: XMLDocument, nsp: string): Element;
export declare function uniqueName(element: Element, parent: Element): string;
