import { LitElement } from 'lit';
import { Ref } from 'lit/directives/ref.js';
import { OscdMenu } from '@omicronenergy/oscd-ui/menu/OscdMenu.js';
import { OscdMenuItem } from '@omicronenergy/oscd-ui/menu/OscdMenuItem.js';
import { OscdIcon } from '@omicronenergy/oscd-ui/icon/OscdIcon.js';
import { FunctionContentPanel, type LNodeSelectionContext } from './function-content-panel.js';
type Point = [number, number];
type FunctionData = {
    element: Element;
    name: string;
    x: number;
    y: number;
    parent?: Element | null;
};
declare const FunctionsLayer_base: typeof LitElement & import("@open-wc/dedupe-mixin").Constructor<import("@open-wc/scoped-elements/types.js").ScopedElementsHost> & import("@open-wc/scoped-elements/types.js").ScopedElementsHostConstructor;
export declare class FunctionsLayer extends FunctionsLayer_base {
    static get scopedElements(): {
        'function-content-panel': typeof FunctionContentPanel;
        'oscd-menu': typeof OscdMenu;
        'oscd-menu-item': typeof OscdMenuItem;
        'oscd-icon': typeof OscdIcon;
    };
    selectedFunctionElement?: Element;
    private contextMenu?;
    private readonly FUNCTION_BOX;
    private readonly FUNCTION_COLORS;
    private readonly FUNCTION_OVERVIEW_GAP;
    doc?: XMLDocument;
    substation?: Element;
    editCount: number;
    gridSize: number;
    disabled: boolean;
    nsp: string;
    placing?: Element;
    placingOffset: Point;
    onStartPlaceFunction?: (element: Element, offset: Point) => void;
    onDonePlaceFunction?: () => void;
    onHoverFunction?: (funcElement: Element | null) => void;
    onSelectFunction?: (element: Element | null) => void;
    onCreateFunctionLink?: (context: LNodeSelectionContext) => void;
    onCancelCreateFunctionLink?: () => void;
    onSelectSourceFunction?: (sourceFunction: Element) => void;
    linkSourceCandidates: Element[];
    selectingLinkSource: boolean;
    showLinks: boolean;
    functions: FunctionData[];
    mouseX: number;
    mouseY: number;
    sldOffsetTop: number;
    sldOffsetLeft: number;
    private hoveredFunction;
    private selectedLink;
    private expandedOverviewDetails;
    svg: SVGSVGElement;
    private readonly menuAnchor;
    coordinatesRef: Ref<HTMLElement>;
    private contextMenuRef;
    private readonly handleKeyDown;
    connectedCallback(): void;
    disconnectedCallback(): void;
    firstUpdated(): void;
    updated(changedProperties: Map<string, any>): void;
    private calculateSldOffset;
    private svgCoordinates;
    positionCoordinates(e: MouseEvent): void;
    private extractFunctions;
    private getSvgDimensions;
    private calculateFunctionBoxWidth;
    private finalizeFunctionPlacement;
    private handleMouseMove;
    private handleFunctionClick;
    private handleFunctionContextMenu;
    private closeContextMenu;
    private startPlacingFunction;
    private handleMoveFunction;
    private handleContainerClick;
    private handleFunctionMouseEnter;
    private handleFunctionMouseLeave;
    private getFunctionLinks;
    private getFunctionBoxGeometry;
    private handleLinkClick;
    private closeLinkOverview;
    private toggleOverviewLinkDetails;
    private renderFunctionLink;
    private renderFunctionLinkOverview;
    private renderFunction;
    render(): import("lit-html").TemplateResult<1>;
    static styles: import("lit").CSSResult;
}
export {};
