import { LitElement } from 'lit';
import { Ref } from 'lit/directives/ref.js';
type Point = [number, number];
type FunctionData = {
    element: Element;
    name: string;
    x: number;
    y: number;
    parent?: Element | null;
};
declare const FunctionsLayer_base: typeof LitElement & import("@open-wc/scoped-elements/lit-element.js").ScopedElementsHostConstructor;
export declare class FunctionsLayer extends FunctionsLayer_base {
    private readonly FUNCTION_BOX;
    private readonly FUNCTION_COLORS;
    doc?: XMLDocument;
    editCount: number;
    gridSize: number;
    disabled: boolean;
    nsp: string;
    placing?: Element;
    placingOffset: Point;
    onStartPlaceFunction?: (element: Element, offset: Point) => void;
    functions: FunctionData[];
    mouseX: number;
    mouseY: number;
    sldOffsetTop: number;
    sldOffsetLeft: number;
    svg: SVGSVGElement;
    coordinatesRef: Ref<HTMLElement>;
    firstUpdated(): void;
    updated(changedProperties: Map<string, any>): void;
    private calculateSldOffset;
    private svgCoordinates;
    positionCoordinates(e: MouseEvent): void;
    private extractFunctions;
    private getSvgDimensions;
    private calculateFunctionBoxWidth;
    private finalizeFunctionPlacement;
    private handleMouseMove;
    private handleFunctionClick;
    private handleContainerClick;
    private renderFunction;
    render(): import("lit-html").TemplateResult<1>;
    static styles: import("lit").CSSResult;
}
export {};
