import { LitElement } from 'lit';
import { Ref } from 'lit/directives/ref.js';
import { OscdMenu } from '@omicronenergy/oscd-ui/menu/OscdMenu.js';
import { OscdMenuItem } from '@omicronenergy/oscd-ui/menu/OscdMenuItem.js';
import { OscdIcon } from '@omicronenergy/oscd-ui/icon/OscdIcon.js';
import { FunctionContentPanel } from './function-content-panel.js';
import { type ProcessedDocument, type ProcessedFunction } from '../../document-processor.js';
type Point = [number, number];
declare const FunctionsLayer_base: typeof LitElement & import("@open-wc/scoped-elements/lit-element.js").ScopedElementsHostConstructor;
export declare class FunctionsLayer extends FunctionsLayer_base {
    static get scopedElements(): {
        'function-content-panel': typeof FunctionContentPanel;
        'oscd-menu': typeof OscdMenu;
        'oscd-menu-item': typeof OscdMenuItem;
        'oscd-icon': typeof OscdIcon;
    };
    selectedFunctionElement?: Element;
    private contextMenu?;
    private readonly FUNCTION_BOX;
    private readonly FUNCTION_COLORS;
    doc?: XMLDocument;
    substation?: Element;
    processedDoc?: ProcessedDocument;
    editCount: number;
    gridSize: number;
    disabled: boolean;
    nsp: string;
    placing?: Element;
    placingOffset: Point;
    onStartPlaceFunction?: (element: Element, offset: Point) => void;
    onDonePlaceFunction?: () => void;
    onHoverFunction?: (funcElement: Element | null) => void;
    onSelectFunction?: (element: Element | null) => void;
    functions: ProcessedFunction[];
    mouseX: number;
    mouseY: number;
    sldOffsetTop: number;
    sldOffsetLeft: number;
    private hoveredFunction;
    svg: SVGSVGElement;
    private readonly menuAnchor;
    coordinatesRef: Ref<HTMLElement>;
    private contextMenuRef;
    private readonly handleKeyDown;
    connectedCallback(): void;
    disconnectedCallback(): void;
    firstUpdated(): void;
    updated(changedProperties: Map<string, any>): void;
    private calculateSldOffset;
    private svgCoordinates;
    positionCoordinates(e: MouseEvent): void;
    private getFunctions;
    private getSvgDimensions;
    private calculateFunctionBoxWidth;
    private finalizeFunctionPlacement;
    private handleMouseMove;
    private handleFunctionClick;
    private handleFunctionContextMenu;
    private closeContextMenu;
    private startPlacingFunction;
    private handleMoveFunction;
    private handleContainerClick;
    private handleFunctionMouseEnter;
    private handleFunctionMouseLeave;
    private renderFunction;
    render(): import("lit-html").TemplateResult<1>;
    static styles: import("lit").CSSResult;
}
export {};
