name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (PR Preview)
        run: npm run build:preview

      - name: Prepare preview directory
        run: |
          cp -r dist preview/
          rsync -av --exclude='plugins.js' demo/ preview/
          sed -i "s|../dist/bay-template-editor.js|./bay-template-editor.js|g" preview/plugins.js

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9 #v1
        with:
          source-dir: preview/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
